- name: Playbook custom EE with azure collections and terraform
  hosts: localhost
  gather_facts: false
  collections:
    - redhat_cop.ee_utilities
  vars:
    ee_registry_dest: autohub.scuderiadidato.com
    ee_registry_username: admin
    ee_registry_password: "{{ lookup('env','CONTROLLER_PASSWORD') }}"
#    ee_base_registry_username: "{{ lookup('env','REDHAT_USER') }}"
#    ee_base_registry_password: "{{ lookup('env','REDHAT_PASS') }}"
#    ee_base_registry_username: "admin"
#    ee_base_registry_password: "{{ lookup('env','CONTROLLER_PASSWORD') }}"
#    ee_base_image: autohub.scuderiadidato.com/azure_terraform_ee
#    ee_builder_image: autohub.scuderiadidato.com/ansible-builder-rhel8
    ee_pull_collections_from_hub: true
    ee_ah_host: autohub.scuderiadidato.com
    ee_ah_token: "aec471c6c5e54c324d781c21ff57eaac218e0c52"
    ee_verbosity: 1
    ee_stream: upstream
    ee_list:
      - name: aap_config_ee
        collections:
          - name: redhat_cop.aap_utilities
          - name: ansible.controller
  roles:
    - redhat_cop.ee_utilities.ee_builder
