---

- hosts: monitor
  gather_facts: true
  become: true
  pre_tasks:

    - name: register subscription manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rh_id }}"
        password: "{{ rh_pass }}"
        auto_attach: true

    - name: enable check_mk webserver port 
      ansible.posix.firewalld:
        port: 5000/tcp
        permanent: true
        state: enabled
        zone: public
        immediate: true
  
  roles:
     - role: tribe29.checkmk.server
       vars:
         checkmk_server_version: "2.1.0p23"
         checkmk_server_edition: cfe
         checkmk_server_sites:
           - name: summitdemo
             version: "{{ checkmk_server_version }}"
             update_conflict_resolution: abort
             state: started
             admin_pw: "{{ check_mk_site_pass }}"
